#
# Build BGP configs in a WAN fabric
#
---
- name: Create & deploy generic configurations
  hosts: all
  connection: local
  gather_facts: no
  vars:
    configs: "{{inventory_dir}}/configs"
  tasks:
  - include_vars: "{{ item }}"
    with_first_found:
      - nodes.yml
      - "{{ inventory_dir }}/nodes.yml"
    tags: [ configs ]
  - include: config_bgp_nc.yml
    tags: [ configs ]
  - include: deploy_bgp_nc.yml