#
# Build configs for IBGP and EBGP routing in a WAN fabric
#
---
- name: Create BGP configurations
  hosts: HUB-ROUTERS,LEAF-ROUTERS
  connection: local
  gather_facts: no
  vars:
    configs: "{{inventory_dir}}/configs"
  tasks:
  - include_vars: "{{ item }}"
    with_first_found:
      - nodes.yml
      - "{{ inventory_dir }}/nodes.yml"
    tags: [ configs ]
  - include: config_bgp.yml
    tags: [ configs ]
